### ISSUE TITLE
Using this library in rebar3 project

### ISSUE THREAD

**Issue by alishir** [sigscale/m3ua#2]
Could you please guide me on how to use this library in a project based on rebar3?

**Comment by vances** [comment]
Sorry, can't help you, I do not use rebar.  I understand it works well
enough these days however for years it did not and my build system, based
on GNU autotools
<https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html>
predates
it.

We use standard GNU coding standards <https://www.gnu.org/prep/standards/>
targets all, install and check with make install creating an Erlang release
<https://www.erlang.org/doc/system/release_structure.html#release-concept>
package.

**Comment by alishir** [comment]
Thanks a lot for your explanation.

**Comment by vances** [comment]
If you want to use rebar it should work just fine with our projects as they
follow all the OTP guidelines.  You'd just be replacing (some of?) the
build system.
